#!/usr/bin/env tsx
/**
 * SRD 5.1 Monster Ingest Script
 *
 * Reads a structured JSON file of SRD monsters and writes
 * data/packs/dnd5e_srd/monsters.json and license.json.
 *
 * Usage:
 *   npx tsx scripts/ingestSrd.ts --input /path/to/srd-monsters.json
 *
 * Input format (array of monster objects):
 *   [
 *     {
 *       "name": "Goblin",
 *       "ac": 15,
 *       "hp": 7,
 *       "cr": "1/4",
 *       "movement": "30 ft",
 *       "attacks": [{ "name": "Scimitar", "bonus": 4, "damage": "1d6+2" }]
 *     },
 *     ...
 *   ]
 *
 * Legal note:
 *   Only ingest content from the D&D 5e SRD (CC BY 4.0).
 *   Do NOT ingest content from the PHB, MM, DMG, or any non-SRD source.
 *   Attribution is automatically written to license.json.
 */

import fs from 'fs';
import path from 'path';

const CC_BY_ATTRIBUTION =
  'This content derives from the System Reference Document 5.1 by Wizards of the Coast LLC, ' +
  'available at https://dnd.wizards.com/resources/systems-reference-document. ' +
  'Licensed under CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/).';

interface SrdMonster {
  name: string;
  ac: number;
  hp: number;
  cr: string;
  movement?: string;
  attacks?: Array<{ name: string; bonus?: number; damage?: string }>;
}

function parseArgs(): { input: string } {
  const args = process.argv.slice(2);
  const inputIdx = args.indexOf('--input');
  if (inputIdx === -1 || !args[inputIdx + 1]) {
    console.error('Usage: npx tsx scripts/ingestSrd.ts --input <path-to-srd-monsters.json>');
    process.exit(1);
  }
  return { input: args[inputIdx + 1] };
}

function validateMonster(m: unknown, index: number): SrdMonster | null {
  if (typeof m !== 'object' || m === null) {
    console.warn(`  [skip] Index ${index}: not an object`);
    return null;
  }
  const obj = m as Record<string, unknown>;
  if (typeof obj.name !== 'string' || !obj.name) {
    console.warn(`  [skip] Index ${index}: missing name`);
    return null;
  }
  if (typeof obj.ac !== 'number' || typeof obj.hp !== 'number') {
    console.warn(`  [skip] ${obj.name}: missing ac or hp`);
    return null;
  }
  if (typeof obj.cr !== 'string') {
    console.warn(`  [skip] ${obj.name}: missing cr`);
    return null;
  }
  return {
    name: obj.name as string,
    ac: obj.ac as number,
    hp: obj.hp as number,
    cr: obj.cr as string,
    movement: typeof obj.movement === 'string' ? obj.movement : '30 ft',
    attacks: Array.isArray(obj.attacks) ? obj.attacks as SrdMonster['attacks'] : [],
  };
}

async function main() {
  const { input } = parseArgs();
  const absInput = path.resolve(input);

  if (!fs.existsSync(absInput)) {
    console.error(`File not found: ${absInput}`);
    process.exit(1);
  }

  console.log(`Reading: ${absInput}`);
  const raw = JSON.parse(fs.readFileSync(absInput, 'utf-8'));
  const source: unknown[] = Array.isArray(raw) ? raw : raw.monsters ?? raw.data ?? [];

  if (!source.length) {
    console.error('No monsters found in input. Expected an array or { monsters: [...] }.');
    process.exit(1);
  }

  const monsters: SrdMonster[] = source
    .map((m, i) => validateMonster(m, i))
    .filter((m): m is SrdMonster => m !== null);

  console.log(`Validated ${monsters.length} / ${source.length} monsters.`);

  const outDir  = path.resolve('data/packs/dnd5e_srd');
  const outFile = path.join(outDir, 'monsters.json');
  const licFile = path.join(outDir, 'license.json');

  fs.mkdirSync(outDir, { recursive: true });

  fs.writeFileSync(outFile, JSON.stringify({
    _note: 'SRD 5.1 monsters — CC-BY 4.0. Generated by scripts/ingestSrd.ts.',
    _license: 'CC-BY-4.0 — see license.json for full attribution text.',
    monsters,
  }, null, 2));

  fs.writeFileSync(licFile, JSON.stringify({
    type: 'CC-BY-4.0',
    attributionText: CC_BY_ATTRIBUTION,
    source: 'https://dnd.wizards.com/resources/systems-reference-document',
    srdVersion: '5.1',
    ingested: new Date().toISOString(),
    monsterCount: monsters.length,
  }, null, 2));

  console.log(`\n✓ Wrote ${monsters.length} monsters → ${outFile}`);
  console.log(`✓ Wrote license → ${licFile}`);
  console.log('\nDone. Attribution text:');
  console.log(`  ${CC_BY_ATTRIBUTION}`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
